module.exports = {
  SET_MUSIC_PLAYER: 'SET_MUSIC_PLAYER',
  DEL_MUSIC_PLAYER: 'DEL_MUSIC_PLAYER',
  
  MUSIC_SET_PLAY: 'MUSIC_SET_PLAY',
  MUSIC_SET_STOP: 'MUSIC_SET_STOP',
  MUSIC_TOGGLE_PLAY: 'MUSIC_TOGGLE_PLAY',

  MUSIC_MOUNT: 'MUSIC_MOUNT',
  MUSIC_UNMOUNT: 'MUSIC_UNMOUNT',

  SET_MUSIC_SEARCH_RESULTS: 'SET_MUSIC_SEARCH_RESULTS',
  SET_MUSIC_SEARCH_PLAYMID: 'SET_MUSIC_SEARCH_PLAYMID'
}