module.exports = {
  MUSIC_SET_PLAY: 'MUSIC_SET_PLAY',
  MUSIC_SET_STOP: 'MUSIC_SET_STOP',
  MUSIC_TOGGLE_PLAY: 'MUSIC_TOGGLE_PLAY',

  MUSIC_MOUNT: 'MUSIC_MOUNT',
  MUSIC_UNMOUNT: 'MUSIC_UNMOUNT',
}